### ISSUE TITLE
topdir.cmi occurs in several directories

### ISSUE THREAD

**Issue by orbifx** [Kakadu/lablqml#28]
```
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/lib/ocaml/compiler-libs, /usr/lib/ocaml
```

A very noisy warning appearing for a lot of compilation targets.

**Comment by Kakadu** [comment]
It is an issue about ocaml itself. I do 

    rm `ocamlc -where`/topdirs.cmi

to suppress that

**Comment by orbifx** [comment]
Is there a permanent fix?

**Comment by Kakadu** [comment]
I think we should patch the compiler. (or check 4.03.0 at least)

**Comment by orbifx** [comment]
Ok. Milestone this issue so that it's not forgotten when the time comes.

**Comment by orbifx** [comment]
This isn't a lablqml issue.
