### ISSUE TITLE
lablqt -> lablqml

### ISSUE THREAD

**Issue by Kakadu** [Kakadu/lablqml#35]
We should rename it and left the old name for @mrvn

**Comment by orbifx** [comment]
What steps do we take to implement this?

**Comment by Kakadu** [comment]
I think we need to rename repo and opam packages.

**Comment by mrvn** [comment]
My package is called ocaml-qt5 so don't rename on my account.

**Comment by orbifx** [comment]
This action would be more for making it clearer to the community the difference between the two projects.

@Kakadu I think ocaml-qml might be a good name.

**Comment by Kakadu** [comment]
Or, it is so big name change! Maybe lablqml?

**Comment by orbifx** [comment]
I didn't know that `labl` stood for `labelled` (which so far our functions aren't :P) so I'm sure it will through other people off too.

**Comment by orbifx** [comment]
Btw I haven't rebased mind branch yet, so either way it's the same changes for me.

**Comment by Kakadu** [comment]
Let's make them labelled!

**Comment by orbifx** [comment]
I searched with _grep_ and removed all critical instanced of `lablqt`.  0bb0d79

But even so, the library still requires `opam remove --force lablqt` to remove.

**Comment by Kakadu** [comment]
@orbifx Have you managed your issues with removal? Can we close it?

**Comment by orbifx** [comment]
I think so. But it's still not lablqml in opam which is causing some confusion in a team I work with.

**Comment by Kakadu** [comment]
How?!?!?! WTF! I do not understand how it is possible

```
➜  ~ evalopam 
/home/kakadu/.opam/4.04.0+fp+flambda/lib/ocaml
2.0.0~beta2
➜  ~ opam  pin
GT.0.0.1        git  git+https://github.com/dboulytchev/GT.git
logger.0.4.2    git  git+https://github.com/dboulytchev/logger.git
➜  ~ opam pin add lablqml https://github.com/Kakadu/lablqml.git
Package lablqml does not exist, create as a NEW package ? [Y/n] Y
[lablqml.~dev] synchronised from git+https://github.com/Kakadu/lablqml.git
[NOTE] Converting format of /home/kakadu/.opam/4.04.0+fp+flambda/.opam-switch/sources/lablqml/opam from 1.2 to 2.0~beta
lablqml is now pinned to git+https://github.com/Kakadu/lablqml.git (version 0.5)

The following actions will be performed:
  ∗  install conf-qt 5.2.1                    [required by lablqml]
  ∗  install lablqml 0.5*
===== ∗  2 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lablqml.0.5] synchronised from git+https://github.com/Kakadu/lablqml.git

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed conf-qt.5.2.1
∗  installed lablqml.0.5
Done.
➜  ~ opam list -a | grep lablqml
655:lablqml                            0.5               pinned to version 0.5 at git+https://github.com/Kakadu/lablqml.git
➜  ~ 

```

**Comment by orbifx** [comment]
OK this issue can be closed as far as I'm concerned.
