### ISSUE TITLE
Some rework in lablqml/ directory

### ISSUE THREAD

**Issue by Kakadu** [Kakadu/lablqml#37]
* remove _oasis
* rename QmlContext.ml
* sane readme

**Comment by Kakadu** [comment]
I did some changes in the `lablqml/`. What do you think, @orbifx ? I'm going to remove `_oasis` file btw soon. It is an artifact from ancient era.

**Comment by orbifx** [comment]
Great thanks! I can use these to rebase my branch.

**Comment by orbifx** [comment]
There is one last thing to close this isssue, having `lablqml/lablqml` is strange. Maybe it should be `labqml/lib`?

**Comment by Kakadu** [comment]
@orbifx seems to be wise idea.

**Comment by orbifx** [comment]
https://github.com/Kakadu/lablqml/pull/47
