### ISSUE TITLE
Site and tutorial links at the end of README.md are broken

### ISSUE THREAD

**Issue by whirm** [Kakadu/lablqml#51]
Both of them 404.

Thanks!

**Comment by orbifx** [comment]
Indeed. I think they were out of date. @Kakadu and I shall bring some back & up to date.

Meanwhile, if you wish to try this project, checkout https://github.com/Kakadu/lablqml/tree/master/demos

There is a new method I need to merge in, which I will write about how to use as well.

**Comment by whirm** [comment]
Yes, I saw. Thanks!

**Comment by ShalokShalom** [comment]
Is there any news?

**Comment by orbifx** [comment]
On what exactly @ShalokShalom ?
