### ISSUE TITLE
conf-qt considers 5.10.0 to be smaller than the required version 5.2.1

### ISSUE THREAD

**Issue by copy** [Kakadu/lablqml#58]
I can't install `conf-qt` on a system which returns `5.10.0` for `qmake -query QT_VERSION`, which is larger than the minimum version of `5.2.1`.

**Comment by Kakadu** [comment]
I'm trying to work that out in https://github.com/ocaml/opam-repository/pull/11247

**Comment by Kakadu** [comment]
It was merged. @copy, please reopen if it still doesn't work.
