### ISSUE TITLE
Max ppxlib version blocks ocaml 4.10 and higher

### ISSUE THREAD

**Issue by sminnee** [Kakadu/lablqml#65]
The ppxlib dependency is capped at 0.9.0, which caps its ocaml dependency at <4.10.0.

This versions of ppxlib is somewhat outdated (the latest is 0.22.0) and the newer versions would allow ocaml 4.10, 4.11, and 4.12.

Is the capping of the ppxlib dependency simply a defensive move, or are there API breakages in ppxlib that would need to be dealt with to allow newer versions of the library to be used?

**Comment by sminnee** [comment]
Sorry, I see that this has probably been resolved in the master branch of this repo, although the latest published tag is v0.6.2 from 2019.

Do you have plans to tag a new version in the coming months?

**Comment by Kakadu** [comment]
I'm working on that in https://github.com/ocaml/opam-repository/pull/18814
